// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCihJ7TG4BzJEOt7Cp8pfeDUbbBuVSFEXQ',
    appId: '1:794141095538:web:c0fd2838d0dc5a935134eb',
    messagingSenderId: '794141095538',
    projectId: 'streamflex-ff624',
    authDomain: 'streamflex-ff624.firebaseapp.com',
    storageBucket: 'streamflex-ff624.appspot.com',
    measurementId: 'G-FEJ5KQHYGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQs_ZgCX8rxieIu4m_5MtaRnycrvBP-DE',
    appId: '1:794141095538:android:b15108f1d7e6bde85134eb',
    messagingSenderId: '794141095538',
    projectId: 'streamflex-ff624',
    storageBucket: 'streamflex-ff624.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDS0xE3N6gI9NWJXmYOpPmYu7C31hTnJ4',
    appId: '1:794141095538:ios:043286818b1b9d3c5134eb',
    messagingSenderId: '794141095538',
    projectId: 'streamflex-ff624',
    storageBucket: 'streamflex-ff624.appspot.com',
    iosBundleId: 'com.example.streamflex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDS0xE3N6gI9NWJXmYOpPmYu7C31hTnJ4',
    appId: '1:794141095538:ios:043286818b1b9d3c5134eb',
    messagingSenderId: '794141095538',
    projectId: 'streamflex-ff624',
    storageBucket: 'streamflex-ff624.appspot.com',
    iosBundleId: 'com.example.streamflex',
  );
}
